name: spendsense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # ✅ UPDATED (important for goal screen image picker)
  image_picker: ^1.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  http: ^1.2.1

  cupertino_icons: ^1.0.8

  file_picker: ^8.1.8+1
  csv: ^5.1.1

  permission_handler: ^11.0.0

  # ✅ LOCAL FIXED NOTIFICATION PLUGIN
  notification_listener_service:
    path: ./notification_listener_service_fixed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/